# Generated by Django 4.0.6 on 2023-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.BigIntegerField()),
                ('count', models.BigIntegerField()),
            ],
        ),
    ]
